//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Musica_mundo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class musica
    {
        public int id { get; set; }
        public string artista { get; set; }
        public string album { get; set; }
        public string pais { get; set; }
        public int id_genero { get; set; }
    
        public virtual genero genero { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
